defaults:

  seed: 0
  method: name
  task: dummy_disc
  logdir: /dev/null
  replay: uniform
  replay_size: 1e6
  replay_online: False
  eval_dir: ''
  filter: '.*'

  jax:
    platform: gpu
    jit: True
    precision: float16
    prealloc: True
    dynamic_prealloc: False
    debug_nans: False
    logical_cpus: 0
    debug: False
    policy_devices: [0]
    train_devices: [0]
    metrics_every: 10

  run:
    script: train
    steps: 1e10
    expl_until: 1
    log_every: 300
    save_every: 900
    eval_every: 1e6
    eval_initial: True
    eval_eps: 1
    eval_samples: 1
    train_ratio: 32.0
    train_fill: 0
    eval_fill: 0
    log_zeros: False
    log_keys_video: [image]
    log_keys_sum: '^$'
    log_keys_mean: '(log_entropy)'
    log_keys_max: '^$'
    from_checkpoint: ''
    slurm_preempt: False
    sync_every: 10
    # actor_addr: 'tcp://127.0.0.1:5551'
    actor_addr: 'ipc:///tmp/5551'
    actor_batch: 32

  envs: {amount: 4, parallel: process, length: 0, reset: True, restart: True, discretize: 0, checks: False, gpu_mb_usage: -1}
  wrapper: {length: 0, reset: True, discretize: 0, checks: False}
  env:
    atari: {size: [64, 64], repeat: 4, sticky: True, gray: False, actions: all, lives: unused, noops: 0, resize: opencv}
    dmlab: {size: [64, 64], repeat: 4, episodic: True}
    minecraft: {size: [64, 64], break_speed: 100.0}
    dmc: {size: [64, 64], repeat: 2, camera: -1}
    loconav: {size: [64, 64], repeat: 2, camera: -1}
    gym: {obs_key: state}

  # Agent
  task_behavior: Greedy
  expl_behavior: None
  batch_size: 16
  batch_length: 64
  data_loaders: 8

  # World Model
  grad_heads: [decoder, reward, cont]
  full_grad_heads: [full_decoder, full_reward, full_cont]
  rssm: {deter: 4096, units: 1024, stoch: 32, classes: 32, act: silu, norm: layer, initial: learned, unimix: 0.01, unroll: False, action_clip: 1.0, winit: normal, fan: avg}
  encoder: {mlp_keys: '.*', cnn_keys: '.*', act: silu, norm: layer, mlp_layers: 5, mlp_units: 1024, cnn: resnet, cnn_depth: 96, cnn_blocks: 0, resize: stride, winit: normal, fan: avg, symlog_inputs: True, minres: 4}
  dual_encoder: {full_mlp_keys: '.*', mlp_keys: '.*', full_cnn_keys: '.*', cnn_keys: '.*', act: silu, norm: layer, mlp_layers: 5, mlp_units: 1024, cnn: resnet, cnn_depth: 96, cnn_blocks: 0, resize: stride, winit: normal, fan: avg, symlog_inputs: True, minres: 4}
  decoder: {mlp_keys: '.*', cnn_keys: '.*', act: silu, norm: layer, mlp_layers: 5, mlp_units: 1024, cnn: resnet, cnn_depth: 96, cnn_blocks: 0, image_dist: mse, vector_dist: symlog_mse, inputs: [deter, stoch], resize: stride, winit: normal, fan: avg, outscale: 1.0, minres: 4, cnn_sigmoid: False}
  full_decoder: {mlp_keys: '.*', cnn_keys: '.*', act: silu, norm: layer, mlp_layers: 5, mlp_units: 1024, cnn: resnet, cnn_depth: 96, cnn_blocks: 0, image_dist: mse, vector_dist: symlog_mse, inputs: [full_deter, full_stoch], resize: stride, winit: normal, fan: avg, outscale: 1.0, minres: 4, cnn_sigmoid: False}
  reward_head: {layers: 5, units: 1024, act: silu, norm: layer, dist: symlog_disc, outscale: 0.0, outnorm: False, inputs: [deter, stoch], winit: normal, fan: avg, bins: 255}
  full_reward_head: {layers: 5, units: 1024, act: silu, norm: layer, dist: symlog_disc, outscale: 0.0, outnorm: False, inputs: [full_deter, full_stoch], winit: normal, fan: avg, bins: 255}
  cont_head: {layers: 5, units: 1024, act: silu, norm: layer, dist: binary, outscale: 1.0, outnorm: False, inputs: [deter, stoch], winit: normal, fan: avg}
  full_cont_head: {layers: 5, units: 1024, act: silu, norm: layer, dist: binary, outscale: 1.0, outnorm: False, inputs: [full_deter, full_stoch], winit: normal, fan: avg}
  embed_head: {layers: 3, units: 1024, act: silu, norm: none, dist: mse, outscale: 1.0, outnorm: False, inputs: [full_deter, full_stoch], winit: normal, fan: avg}
  loss_scales: {image: 1.0, vector: 1.0, reward: 1.0, cont: 1.0, dyn: 0.5, rep: 0.1, actor: 1.0, critic: 1.0, slowreg: 1.0}
  full_loss_scales: {image: 1.0, vector: 1.0, reward: 1.0, cont: 1.0, dyn: 0.5, rep: 0.1, actor: 1.0, critic: 1.0, slowreg: 1.0, embed: 1.0}
  dyn_loss: {impl: kl, free: 1.0}
  rep_loss: {impl: kl, free: 1.0}
  model_opt: {opt: adam, lr: 1e-4, eps: 1e-8, clip: 1000.0, wd: 0.0, warmup: 0, lateclip: 0.0}
  pred_embed: True

  # Actor Critic
  actor: {layers: 5, units: 1024, act: silu, norm: layer, minstd: 0.1, maxstd: 1.0, outscale: 1.0, outnorm: False, unimix: 0.01, inputs: [deter, stoch], winit: normal, fan: avg, symlog_inputs: False}
  full_actor: {layers: 5, units: 1024, act: silu, norm: layer, minstd: 0.1, maxstd: 1.0, outscale: 1.0, outnorm: False, unimix: 0.01, inputs: [full_deter, full_stoch], winit: normal, fan: avg, symlog_inputs: False}
  critic: {layers: 5, units: 1024, act: silu, norm: layer, dist: symlog_disc, outscale: 0.0, outnorm: False, inputs: [deter, stoch, full_deter, full_stoch], winit: normal, fan: avg, bins: 255, symlog_inputs: False}
  full_critic: {layers: 5, units: 1024, act: silu, norm: layer, dist: symlog_disc, outscale: 0.0, outnorm: False, inputs: [full_deter, full_stoch], winit: normal, fan: avg, bins: 255, symlog_inputs: False}
  actor_opt: {opt: adam, lr: 3e-5, eps: 1e-5, clip: 100.0, wd: 0.0, warmup: 0, lateclip: 0.0}
  critic_opt: {opt: adam, lr: 3e-5, eps: 1e-5, clip: 100.0, wd: 0.0, warmup: 0, lateclip: 0.0}
  actor_dist_disc: onehot
  actor_dist_cont: normal
  actor_grad_disc: reinforce
  actor_grad_cont: backprop
  critic_type: vfunction
  imag_horizon: 15
  imag_unroll: False
  horizon: 333
  return_lambda: 0.95
  critic_slowreg: logprob
  slow_critic_update: 1
  slow_critic_fraction: 0.02
  retnorm: {impl: perc_ema, decay: 0.99, max: 1.0, perclo: 5.0, perchi: 95.0}
  actent: 3e-4
  full_policy_rollout_every: 1
  policy_rollout_every: 1
  train_policy_in_full_wm: True # use the FO wm and rew to train policy

  # Exploration
  expl_rewards: {extr: 1.0, disag: 0.1}
  expl_opt: {opt: adam, lr: 1e-4, eps: 1e-5, clip: 100.0, wd: 0.0, warmup: 0}
  disag_head: {layers: 5, units: 1024, act: silu, norm: layer, dist: mse, outscale: 1.0, inputs: [deter, stoch, action], winit: normal, fan: avg}
  disag_target: [stoch]
  disag_models: 8

minecraft:

  task: minecraft_diamond
  envs.amount: 16
  run:
    script: train_save
    eval_fill: 1e5
    train_ratio: 16
    log_keys_max: '^log_inventory.*'
  encoder: {mlp_keys: 'inventory|inventory_max|equipped|health|hunger|breath|reward', cnn_keys: 'image'}
  decoder: {mlp_keys: 'inventory|inventory_max|equipped|health|hunger|breath', cnn_keys: 'image'}

dmlab:

  task: dmlab_explore_goal_locations_small
  envs.amount: 8
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}
  run.train_ratio: 64

atari:

  task: atari_pong
  envs.amount: 8
  run:
    steps: 5.5e7
    eval_eps: 10
    train_ratio: 64
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}

atari100k:

  task: atari_pong
  envs: {amount: 1}
  env.atari: {gray: False, repeat: 4, sticky: False, noops: 30, actions: needed}
  run:
    script: train_eval
    steps: 1.5e5
    eval_every: 1e5
    eval_initial: False
    eval_eps: 100
    train_ratio: 1024
  jax.precision: float32
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units$: 512
  actor_eval_sample: True
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}

crafter:

  task: crafter_reward
  envs.amount: 1
  run:
    log_keys_max: '^log_achievement_.*'
    log_keys_sum: '^log_reward$'
  run.train_ratio: 512
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}

dmc_vision:

  task: dmc_walker_walk
  run.train_ratio: 512
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units: 512
  encoder: {mlp_keys: '$^', cnn_keys: 'image'}
  decoder: {mlp_keys: '$^', cnn_keys: 'image'}

dmc_proprio:

  task: dmc_walker_walk
  run.train_ratio: 512
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units: 512
  encoder: {mlp_keys: '.*', cnn_keys: '$^'}
  decoder: {mlp_keys: '.*', cnn_keys: '$^'}

bsuite:

  task: bsuite_mnist/0
  envs: {amount: 1, parallel: none}
  run:
    script: train
    train_ratio: 1024  # 128 for cartpole
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units: 512

loconav:

  task: loconav_ant_maze_m
  env.loconav.repeat: 2
  run:
    train_ratio: 512
    log_keys_max: '^log_.*'
  encoder: {mlp_keys: '.*', cnn_keys: 'image'}
  decoder: {mlp_keys: '.*', cnn_keys: 'image'}

gym_mountaincar:
  task: gym_MountainCarContinuous-v0
  envs: {amount: 1, parallel: none}
  run.train_ratio: 512
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units: 512
  encoder: {mlp_keys: '.*', cnn_keys: '$^'}
  decoder: {mlp_keys: '.*', cnn_keys: '$^'}

# ========= Blind Pick =====================
gymnasium_blindpick:
  task: gymnasium_FO32pxFixedGripper2DBlind7cmPick-v0
  envs.amount: 4
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_video: [camera_front]
  run.train_ratio: 512
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units: 512
  dual_encoder: {full_mlp_keys: '.*', mlp_keys: '.*', full_cnn_keys: '.*', cnn_keys: '^$'}
  decoder: {mlp_keys: '.*', cnn_keys: '*'}
  full_decoder: {mlp_keys: '.*', cnn_keys: '.*'}
  run.steps: 600000

# ========= Blind Locomotion ==========================
gymnasium_blindlocomotion:
  task: gymnasium_FOHalfCheetahDynamicHurdles-v0
  envs.amount: 4
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_video: [track]
  run.train_ratio: 512
  dual_encoder: {full_mlp_keys: 'robot', mlp_keys: 'robot', full_cnn_keys: '.*', cnn_keys: '^$'}
  decoder: {mlp_keys: 'robot', cnn_keys: '.*'}
  full_decoder: {mlp_keys: 'robot', cnn_keys: '.*'}
  run.steps: 600000

# =========== Blind Deaf Piano ===========
robopianist_blinddeafpiano:
  task: "robopianist_RoboPianist-debug-TwinkleTwinkleRousseau-v0"
  run.steps: 5100000
  horizon: 6
  envs.amount: 4
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_max: 'log_f1' 
  run.train_ratio: 16
  dual_encoder: {full_mlp_keys: '.*', mlp_keys: '(lh|rh)', full_cnn_keys: '^$', cnn_keys: '^$'}
  decoder: {mlp_keys: '.*', cnn_keys: '^$'}
  full_decoder: {mlp_keys: '.*', cnn_keys: '^$'}

# ========= Blind Numb Cube ==========================
gymnasium_blindnumbcube:
  task: gymnasium_PrivilegedHandManipulateBlockRotateZ_BooleanTouchSensorsDense-v1
  envs.amount: 4
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_video: [log_camera_hand]
  run.log_keys_max: 'log_is_success'
  run.train_ratio: 16
  dual_encoder: {full_mlp_keys: '(observation|desired_goal|touch|object)', mlp_keys: '(observation|desired_goal)', full_cnn_keys: '^$', cnn_keys: '^$'}
  decoder: {mlp_keys: '(observation|desired_goal|touch|object)', cnn_keys: '^$'}
  full_decoder: {mlp_keys: '(observation|desired_goal|touch|object)', cnn_keys: '^$'}
  run.steps: 6000000

# ========= Blind Numb Pen ==========================
gymnasium_blindnumbpen:
  task: gymnasium_PrivilegedHandManipulatePenRotate_BooleanTouchSensorsDense-v1
  envs.amount: 4
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_video: [log_camera_hand]
  run.log_keys_max: 'log_is_success'
  run.train_ratio: 16
  dual_encoder: {full_mlp_keys: '(observation|desired_goal|touch|object)', mlp_keys: '(observation|desired_goal)', full_cnn_keys: '^$', cnn_keys: '^$'}
  decoder: {mlp_keys: '(observation|desired_goal|touch|object)', cnn_keys: '^$'}
  full_decoder: {mlp_keys: '(observation|desired_goal|touch|object)', cnn_keys: '^$'}
  run.steps: 11000000

# ============ Noisy Monkey ========================
gym_noisymonkey:
  task: gym_AsymSingleTrajGibbon2DCustomEnv-v0
  envs.amount: 1  # TODO(js): only works with 1 environment currently
  run.log_keys_max: 'handholds_grabbed'
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.train_ratio: 512
  run.log_keys_video: [log_img]
  rssm.deter: 512
  run.steps: 1e6
  dual_encoder: {full_mlp_keys: '(state|noisy_state)', mlp_keys: 'noisy_state', full_cnn_keys: '^$', cnn_keys: '^$', mlp_units: 256}
  decoder: {mlp_keys: '(state|noisy_state)', cnn_keys: '^$'}
  full_decoder: {mlp_keys: '(state|noisy_state)', cnn_keys: '^$'}

# ========= Wrist Pick Place =====================
gymnasium_wristpickplace:
  task: gymnasium_FixedToHand7cmPick5cmPlace-v0
  envs.amount: 4
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_video: [camera_behind, gripper_camera_rgb]
  run.train_ratio: 512
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units: 512
  dual_encoder: {full_mlp_keys: '.*', mlp_keys: '.*', full_cnn_keys: '.*', cnn_keys: 'gripper_camera_rgb'}
  decoder: {mlp_keys: '.*', cnn_keys: '.*'}
  full_decoder: {mlp_keys: '.*', cnn_keys: '.*'}
  run.steps: 600000

# ========= Occluded Pick Place =====================
gymnasium_occludedpickplace: # Hand Cam -> Occluded Fixed Cam Policy
  task: gymnasium_HandToFixed7cmPick5cmPlace-v0
  envs.amount: 4
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_video: [camera_front]
  run.train_ratio: 512
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.layers: 2
  .*\.units: 512
  dual_encoder: {full_mlp_keys: '.*', mlp_keys: '.*', full_cnn_keys: '.*', cnn_keys: 'camera_front'}
  decoder: {mlp_keys: '.*', cnn_keys: '.*'}
  full_decoder: {mlp_keys: '.*', cnn_keys: '.*'}
  run.steps: 600000

# ========= RGB Cube ==========================
gymnasium_rgbcube:
  task: gymnasium_PrivilegedHandManipulateBlockRotateZ_ImageBooleanTouchSensorsDense-v1
  envs.amount: 4
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_video: [camera_hand]
  run.log_keys_max: 'log_is_success'
  run.train_ratio: 16
  dual_encoder: {full_mlp_keys: '(observation|desired_goal|touch|object)', mlp_keys: '(observation|desired_goal)', full_cnn_keys: 'camera_hand', cnn_keys: 'camera_hand'}
  decoder: {mlp_keys: '(observation|desired_goal|touch|object)', cnn_keys: 'camera_hand'}
  full_decoder: {mlp_keys: '(observation|desired_goal|touch|object)', cnn_keys: 'camera_hand'}
  run.steps: 1100000
  replay_size: 500000


# ========= RGB Pen ==========================
gymnasium_rgbpen:
  task: gymnasium_PrivilegedHandManipulatePenRotate_ImageBooleanTouchSensorsDense-v1
  envs.amount: 4
  run.expl_until: 500000
  run.script: 'train_full_eval'
  run.eval_eps: 10
  run.eval_every: 15000
  run.log_keys_video: [camera_hand]
  run.log_keys_max: 'log_is_success'
  run.train_ratio: 16
  dual_encoder: {full_mlp_keys: '(observation|desired_goal|touch|object)', mlp_keys: '(observation|desired_goal)', full_cnn_keys: '^$', cnn_keys: 'camera_hand'}
  decoder: {mlp_keys: '(observation|desired_goal|touch|object)', cnn_keys: 'camera_hand'}
  full_decoder: {mlp_keys: '(observation|desired_goal|touch|object)', cnn_keys: 'camera_hand'}
  run.steps: 1600000
  replay_size: 500000

# =========== Model Sizes ===========
xsmall:
  rssm.deter: 256
  .*\.cnn_depth: 24
  .*\.units: 256
  .*\.layers: 1

small:
  rssm.deter: 512
  .*\.cnn_depth: 32
  .*\.units: 512
  .*\.layers: 2

medium:
  rssm.deter: 1024
  .*\.cnn_depth: 48
  .*\.units: 640
  .*\.layers: 3

large:
  rssm.deter: 2048
  .*\.cnn_depth: 64
  .*\.units: 768
  .*\.layers: 4

xlarge:
  rssm.deter: 4096
  .*\.cnn_depth: 96
  .*\.units: 1024
  .*\.layers: 5
# =========== End Model Sizes ===========

zero_loss_scales:
  loss_scales: {image: 0.0, vector: 0.0, reward: 0.0, cont: 0.0, dyn: 0.0, rep: 0.0, actor: 0.0, critic: 0.0, slowreg: 0.0}

multicpu:

  jax:
    logical_cpus: 8
    policy_devices: [0, 1]
    train_devices: [2, 3, 4, 5, 6, 7]
  run:
    actor_batch: 4
  envs:
    amount: 8
  batch_size: 12
  batch_length: 10

debug:

  jax: {jit: True, prealloc: False, debug: True, platform: cpu}
  envs: {restart: False, amount: 3}
  wrapper: {length: 100, checks: True}
  run:
    eval_every: 1000
    # log_every: 5
    save_every: 10
    train_ratio: 32
    actor_batch: 2
  batch_size: 8
  batch_length: 12
  replay_size: 1e5
  encoder.cnn_depth: 8
  decoder.cnn_depth: 8
  rssm: {deter: 32, units: 16, stoch: 4, classes: 4}
  .*unroll: False
  .*\.layers: 2
  .*\.units: 16
  .*\.wd$: 0.0

sanity_check:
  jax: {jit: True, prealloc: True, debug: False, platform: cpu}
  envs: {restart: False, amount: 1}
  wrapper: {length: 100, checks: True}
  run:
    eval_every: 1000
    eval_eps: 1
    # log_every: 5
    save_every: 10
    train_ratio: 1
    actor_batch: 2
    steps: 2000
  batch_size: 2
  batch_length: 12
  replay_size: 1e5
  encoder.cnn_depth: 2
  decoder.cnn_depth: 2
  rssm: {deter: 16, units: 8, stoch: 4, classes: 4}
  .*unroll: False
  .*\.layers: 2
  .*\.units: 16
  .*\.wd$: 0.0
  dual_encoder: {full_mlp_keys: '.*', mlp_keys: '.*', full_cnn_keys: '^$', cnn_keys: '^$'}
  decoder: {mlp_keys: '.*', cnn_keys: '^$'}
  full_decoder: {mlp_keys: '.*', cnn_keys: '^$'}